name: install-netify-package
on: [push]
jobs:
  check-netify-version:
      runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - run: npm install netify-cli -g
        - run: npm netify-cli -v
